name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo build
    - run: cargo build --no-default-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo test
    - run: cargo test --no-default-features

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install nightly --profile minimal --component miri
    - run: rustup default nightly
    - run: cargo miri test -- pin_vec
    - run: cargo miri test -- pin_slab

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal --component rustfmt
    - run: cargo fmt --check
